#!/bin/bash

if (( $# == 0 )); then
	echo -e  "cibuilder.sh - Cinder for Empscripten wrapper script"
	echo -e "usage examples:"
	echo -e "\tcibuilder.sh -j 4 -b Debug"
	echo -e "\tcibuilder.sh clean -b Debug"
	echo -e ""
	echo -e "options:"
	echo -e "\tclean    Cleans the build for specified build type"
	echo -e "\t-b [str] Build type, ex: -b Debug,Release "
	echo -e "\t-j [n]   Number of compile processes, ex: -j 4"
	echo -e ""
	echo -e "flags:"
	echo -e "\t-r       Rebuild instead of full build"
	echo -e "\t-v       Turns on verbose mode"
	exit 0
fi


if [[ "$(uname -s)" == *"Linux"* ]]; then
	SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
	NUMPROCS=$(nproc)
elif [[ "$(uname -s)" == *"Darwin"* ]]; then
	SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
	NUMPROCS=$(sysctl -n hw.ncpu)
else
	SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
	NUMPROCS=$(nproc)
fi

CLEAN=false
BUILD_TYPES=(Debug)
OPENGL_PLAT="es3"
FULLBUILD=true
VERBOSE=
APP_BUILD=false
SAMPLES=


# Process arguments
while (( $# >= 1 ))
do
	arg=$1

	case $arg in
		# Clean
		clean)
			CLEAN=true
			shift 1
		;;

		# Build types
		-b)
			# Clear array
			BUILD_TYPES=()
			# Split string into tokens
			tokens=(${2//,/ })
			# Parse build types
			for tok in ${tokens[@]}; do
				build=$(echo $tok | tr '[:upper:]' '[:lower:]')
				case $build in
					debug)
						BUILD_TYPES+=(Debug)
					;;

					release)
						BUILD_TYPES+=(Release)
					;;

					*)
						echo "-b Unknown build type: $build"
						exit 1
					;;
				esac
			done
			shift 2
		;;

		# Number of build processes
		-j)
			# Make sure this is a number
			if [[ $2 = *[[:digit:]]* ]]; then
				NUMPROCS=$2
			else
				echo "-j requires a number"
				exit 1
			fi
			shift 2
		;;

		# Rebuild
		-r)
			FULLBUILD=false
			shift 1
		;;

		# Verbose
		-v)
			VERBOSE="VERBOSE=1"
			shift 1
		;;

		?*)
			echo "Unknown parameter: ${arg}"
			exit 1
		;;
	esac
done

for build in ${BUILD_TYPES[@]}; do
	build_type=${build}
	build_dir=$(pwd)/${build}/${OPENGL_PLAT}

	if [ ${APP_BUILD} == true ]; then
		build_dir=$(pwd)/${build}/${OPENGL_PLAT}
	else
		build_dir=${SCRIPT_DIR}/../../emscripten/${build}/${OPENGL_PLAT}
	fi

	# Clean
	if [ ${CLEAN} == true ] || [ ${FULLBUILD} == true ]; then
		echo "Cleaning ${build_type} ..."
		if [ -d "${build_dir}" ]; then
			rm -rf "${build_dir}"
			echo "...deleted dir: ${build_dir}"
		fi

		if [ ${CLEAN} == true ]; then
			exit 0
		fi
	fi

	# Check for CMakeLists.txt
	cmake_file_path="${SCRIPT_DIR}/../../emscripten/CMakeLists.txt"
	if [ ${APP_BUILD} == true ]; then
		cmake_file_path="$(pwd)/CMakeLists.txt"
	fi

	if [ ! -f "${cmake_file_path}" ]; then
		echo "ERROR: Couldn't find CMakeLists.txt in $(cmake_file_path)"
		exit
	fi

	# Build
	echo "---------------------------------------------------------------------------------"
	echo "Building Cinder in ${build_type} mode with ${NUMPROCS} compile processes"

	if [ ! -d "${build_dir}" ]; then
		mkdir -p ${build_dir}
		echo "...created dir: ${build_dir}"
	fi

	cd ${build_dir}

	if [ "$(uname -s)" == *"Linux"* ] || [ "$(uname -s)" == *"Darwin"* ]; then
		if [ ${FULLBUILD} == true ] || [ ! -f "${build_dir}/CMakeCache.txt" ]; then
			echo "CMAKE COMMAND: cmake .. -DCMAKE_TOOLCHAIN_FILE=${EMSCRIPTEN}/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_BUILD_TYPE=${build_type} ${GLES} ${SAMPLES}"

			emcmake cmake ../.. -DCMAKE_TOOLCHAIN_FILE=${EMSCRIPTEN}/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_BUILD_TYPE=${build_type} ${GLES} ${SAMPLES}
		fi
		make -j ${NUMPROCS} ${VERBOSE}

		echo -e ""
	else
		if [ ${FULLBUILD} == true ] || [ ! -f "${build_dir}/CMakeCache.txt" ]; then
			echo "CMAKE COMMAND IS :emcmake cmake ../.. -DCMAKE_MAKE_PROGRAM=mingw32-make -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=${EMSCRIPTEN}/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_BUILD_TYPE=${build_type} ${GLES} ${SAMPLES}"
			# add -G "Unix Makefiles" to generate makefile instead of Visual studio stuff.
			emcmake cmake ../.. -DCMAKE_MAKE_PROGRAM=mingw32-make -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=${EMSCRIPTEN}/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_BUILD_TYPE=${build_type} ${GLES} ${SAMPLES}
		fi
		# TODO any other make commands to try? 
		mingw32-make -j ${NUMPROCS} ${VERBOSE} || make -j ${NUMPROCS} ${VERBOSE} || echo "An error occured - remember you need to have a \"make\" program installed. It's also possible one of the core files had an error while building."
		echo -e ""
	fi

done
