#version: 1.0.{build}

build:
  parallel: true
  project: proj/vc2019/cinder.sln

platform:
    - x64

configuration:
  - Debug
  - Release
#  - Debug_ANGLE
#  - Release_ANGLE

image: 
  - Visual Studio 2019

clone_depth: 10

before_test:
  - msbuild test\unit\vc2019\unit.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

# in the future we'll need to figure out how to tell what version (v140, v150) we are targeting from within AppVeyor
test_script:
  - set ARCH_FOLDER=%platform%
  - echo Binary resolving to test\unit\vc2019\build\v142\%configuration%\%ARCH_FOLDER%\CinderUnitTests.exe
  - test\unit\vc2019\build\v142\%configuration%\%ARCH_FOLDER%\CinderUnitTests.exe