---
format_version: '8'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: macos
trigger_map:
  - push_branch: "*"
    workflow: primary
  - pull_request_source_branch: "*"
    workflow: primary
workflows:
  primary:
    steps:
      - activate-ssh-key@4:
          run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
      - git-clone@4: {}
      - cache-pull@2: {}
      - script@1:
          title: Do anything with Script step
      - certificate-and-profile-installer@1: {}
      - recreate-user-schemes@1:
          inputs:
            - project_path: "$BITRISE_PROJECT_PATH"
      - xcode-archive-mac@1:
          inputs:
            - project_path: "$BITRISE_PROJECT_PATH"
            - scheme: "$BITRISE_SCHEME"
            - export_method: "$BITRISE_EXPORT_METHOD"
      - deploy-to-bitrise-io@1: {}
      - cache-push@2: {}
app:
  envs:
    - opts:
        is_expand: false
      BITRISE_PROJECT_PATH: test/AppTest/xcode/AppTest.xcodeproj
    - opts:
        is_expand: false
      BITRISE_SCHEME: AppTest
    - opts:
        is_expand: false
      BITRISE_EXPORT_METHOD: app-store
