language: cpp
git:
  depth: 1
  submodules: false

fast_finish: false

matrix:
  include:

    # linux version have unique dependencies, so we set them up individually
    # linux version have unique dependencies, so we set them up individually
    - os: linux
      dist: trusty
      compiler: gcc
      sudo: required
      addons: 
        apt:
          update: true
      env:
        - TARGET="trusty"
        - DESCRIPTION="Ubuntu Trusty build/test via CMake & gcc"
        - MATRIX_EVAL="CC=gcc && CXX=g++"

    - os: linux
      dist: trusty
      compiler: clang
      sudo: required
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            # clang requires newer standard library to work properly
            - g++-4.9
      env:
        - TARGET="trusty"
        - DESCRIPTION="Ubuntu Trusty build/test via CMake & clang"
        - MATRIX_EVAL="CC=clang && CXX=clang++"

    - os: linux
      dist: trusty
      compiler: clang
      sudo: required
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - clang++-3.5
      env:
        - TARGET="trusty"
        - DESCRIPTION="Ubuntu Trusty build/test via CMake & clang-3.5"
        - MATRIX_EVAL="CC=clang-3.5 && CXX=clang++-3.5"

    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - TARGET="trusty"
         - DESCRIPTION="Ubuntu Trusty build/test via CMake & g++5"
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
         - TARGET="trusty"
         - DESCRIPTION="Ubuntu Trusty build/test via CMake & g++6"
         - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"


    # OS X Xcode
    - os: osx
      osx_image: xcode9.2
      env:
        - TOOL="xcode-osx"
        - DESCRIPTION="OS X build/test via Xcode"
    - os: osx
      osx_image: xcode8.3
      env:
        - TOOL="xcode-osx"
        - DESCRIPTION=OS X build/test via Xcode"
    - os: osx
      osx_image: xcode7.3
      env:
        - TOOL="xcode-osx"
        - DESCRIPTION=OS X build/test via Xcode"

    # iOS Xcode
    - os: osx
      osx_image: xcode9.2
      env:
        - TOOL="xcode-ios"
        - DESCRIPTION="OS X build/test via Xcode"
    - os: osx
      osx_image: xcode8.3
      env:
        - TOOL="xcode-ios"
        - DESCRIPTION=OS X build/test via Xcode"
    - os: osx
      osx_image: xcode7.3
      env:
        - TOOL="xcode-ios"
        - DESCRIPTION=OS X build/test via Xcode"

    # iOS-Sim Xcode
    - os: osx
      osx_image: xcode9.2
      env:
        - TOOL="xcode-ios-sim"
        - DESCRIPTION="OS X build/test via Xcode"
    - os: osx
      osx_image: xcode8.3
      env:
        - TOOL="xcode-ios-sim"
        - DESCRIPTION=OS X build/test via Xcode"
    - os: osx
      osx_image: xcode7.3
      env:
        - TOOL="xcode-ios-sim"
        - DESCRIPTION=OS X build/test via Xcode"

    # OS X CMake
    - os: osx
      osx_image: xcode9.2
      env:
        - TOOL="cmake"
        - DESCRIPTION="OS X build/test via CMake"
    - os: osx
      osx_image: xcode8.3
      env:
        - TOOL="cmake"
        - DESCRIPTION="OS X build/test via CMake"
    - os: osx
      osx_image: xcode7.3
      env:
        - TOOL="cmake"
        - DESCRIPTION="OS X build/test via CMake"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      eval "${MATRIX_EVAL}";
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      git submodule update --init --recursive;
    fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      tools/linux/scripts/"$TARGET"-install-deps.sh;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$TOOL" == "cmake" ]]; then
      tools/osx/scripts/cmake-brew-install.sh;
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      tools/ci/cmake_test.sh;
    elif  [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$TOOL" == "cmake" ]]; then
      tools/ci/cmake_test.sh;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$TOOL" == "xcode-osx" ]]; then
      tools/ci/xcode_osx_test.sh;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$TOOL" == "xcode-ios" ]]; then
      proj/xcode/ios-build-xcpretty.sh;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$TOOL" == "xcode-ios-sim" ]]; then
      proj/xcode/iossim-build-xcpretty.sh;
    fi

