#!/bin/sh
SAVED_DIR=`pwd`
NUM_PROCS=4
ARCH=arm

API_LEVEL=19

PLATFORM=android-$API_LEVEL
BUILD_TYPE=Debug
rm -rf ./build/$ARCH/$PLATFORM/$BUILD_TYPE
mkdir -p ./build/$ARCH/$PLATFORM/$BUILD_TYPE
cd ./build/$ARCH/$PLATFORM/$BUILD_TYPE
cmake ../../../.. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DNDK_ARCH=$ARCH -DNDK_PLATFORM=$API_LEVEL
make -j $NUM_PROCS VERBOSE=1

cd $SAVED_DIR
PLATFORM=android-$API_LEVEL
BUILD_TYPE=Release
rm -rf ./build/$ARCH/$PLATFORM/$BUILD_TYPE
mkdir -p ./build/$ARCH/$PLATFORM/$BUILD_TYPE
cd ./build/$ARCH/$PLATFORM/$BUILD_TYPE
cmake ../../../.. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DNDK_ARCH=$ARCH -DNDK_PLATFORM=$API_LEVEL
make -j $NUM_PROCS VERBOSE=1

API_LEVEL=21

PLATFORM=android-$API_LEVEL
BUILD_TYPE=Debug
rm -rf ./build/$ARCH/$PLATFORM/$BUILD_TYPE
mkdir -p ./build/$ARCH/$PLATFORM/$BUILD_TYPE
cd ./build/$ARCH/$PLATFORM/$BUILD_TYPE
cmake ../../../.. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DNDK_ARCH=$ARCH -DNDK_PLATFORM=$API_LEVEL
make -j $NUM_PROCS VERBOSE=1

cd $SAVED_DIR
PLATFORM=android-$API_LEVEL
BUILD_TYPE=Release
rm -rf ./build/$ARCH/$PLATFORM/$BUILD_TYPE
mkdir -p ./build/$ARCH/$PLATFORM/$BUILD_TYPE
cd ./build/$ARCH/$PLATFORM/$BUILD_TYPE
cmake ../../../.. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DNDK_ARCH=$ARCH -DNDK_PLATFORM=$API_LEVEL
make -j $NUM_PROCS VERBOSE=1

