
if(NOT WIN32)
  string(ASCII 27 Esc)
  set(ColorReset    "${Esc}[m"     )
  set(ColorBold     "${Esc}[1m"    )
  set(Red           "${Esc}[31m"   )
  set(Green         "${Esc}[32m"   )
  set(Yellow        "${Esc}[33m"   )
  set(Blue          "${Esc}[34m"   )
  set(Magenta       "${Esc}[35m"   )
  set(Cyan          "${Esc}[36m"   )
  set(White         "${Esc}[37m"   )
  set(BoldRed       "${Esc}[1;31m" )
  set(BoldGreen     "${Esc}[1;32m" )
  set(BoldYellow    "${Esc}[1;33m" )
  set(BoldBlue      "${Esc}[1;34m" )
  set(BoldMagenta   "${Esc}[1;35m" )
  set(BoldCyan      "${Esc}[1;36m" )
  set(BoldWhite     "${Esc}[1;37m" )
endif()

set( CINDER_INC_DIR ${CINDER_DIR}/include )
set( CINDER_SRC_DIR ${CINDER_DIR}/src )
set( BOOST_INC_DIR  ${CINDER_DIR}/boost )

set( CINDER_TOOLCHAIN_CLANG true )

if( CINDER_TOOLCHAIN_CLANG )
    set(CMAKE_TOOLCHAIN_PREFIX "llvm-" ) 
    set(CMAKE_C_COMPILER                      "clang")
    set(CMAKE_CXX_COMPILER                    "clang++")

    set(CMAKE_C_FLAGS_INIT                    "-Wall -std=c99")
    set(CMAKE_C_FLAGS_DEBUG_INIT              "-g")
    set(CMAKE_C_FLAGS_MINSIZEREL_INIT         "-Os -DNDEBUG")
    set(CMAKE_C_FLAGS_RELEASE_INIT            "-O4 -DNDEBUG")
    set(CMAKE_C_FLAGS_RELWITHDEBINFO_INIT     "-O2 -g")
    set(CMAKE_C_FLAGS                         "${CMAKE_C_FLAGS} -fmessage-length=0 ")

    set(CMAKE_CXX_FLAGS_INIT                  "-Wall")
    set(CMAKE_CXX_FLAGS_DEBUG_INIT            "-g")
    set(CMAKE_CXX_FLAGS_MINSIZEREL_INIT       "-Os -DNDEBUG")
    set(CMAKE_CXX_FLAGS_RELEASE_INIT          "-O4 -DNDEBUG")
    set(CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT   "-O2 -g")
    set(CMAKE_CCC_FLAGS                       "${CMAKE_C_FLAGS} -fmessage-length=0 ")
endif()

set( CXX_FLAGS "-stdlib=libc++ -std=c++11" )
set( CMAKE_CXX_FLAGS_DEBUG    "${CXX_FLAGS} -g -fexceptions -frtti" )
set( CMAKE_CXX_FLAGS_RELEASE  "${CXX_FLAGS} -Os -fexceptions -frtti -ffast-math" )
