function( ci_log_v )
	if( CINDER_VERBOSE )
		set( msg )
		foreach( i RANGE ${ARGC} )
			set( msg "${msg}${ARGV${i}}" )
		endforeach()
		message( VERBOSE " |cinder| ${msg}" )
	endif()
endfunction()

function( ci_log_i )
	set( msg )
	foreach( i RANGE ${ARGC} )
		set( msg "${msg}${ARGV${i}}" )
	endforeach()
	message( INFO " |cinder| ${msg}" )
endfunction()
