# Recursively finds directories that end in "proj/cmake", which contain a CMakeLists.txt (ex. samples and tests)
macro( findCMakeDirs RESULT_PATHS BASE_PATH )
	file( GLOB results "${BASE_PATH}/*" )
	foreach( f ${results} )
		if( IS_DIRECTORY "${f}" )
			if( f MATCHES ".*/proj/cmake$" )
				set( ${RESULT_PATHS} ${${RESULT_PATHS}} ${f} )
			else()
				findCMakeDirs( ${RESULT_PATHS} ${f} )
			endif()
		endif()
	endforeach()
endmacro( findCMakeDirs RESULT_PATHS BASE_PATH )
