#!/bin/bash

# Requires the bleeding edge Emscripten:
#	cd ${YOUR_EMSCRIPTEN_DIR}
#   ./emsdk update
#   ./emsdk install --build=Release sdk-incoming-64bit
#   ./emsdk activate --build=Release sdk-incoming-64bit
#
# Source the emsdk_env.sh before you do anything:
#   source ${YOUR_EMSCRIPTEN_DIR}/emsdk_env.sh
# 

if [ "$#" -eq 0 ]; then
	../tools/emscripten/cibuilder -b Debug
else
	../tools/emscripten/cibuilder "$@"
fi
